export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import {SanityLive} from '../sanity/lib/live'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <SanityLive />
      </body>
    </html>
  )
}
